services:
  clanimg-web:
    build:
      context: .
      dockerfile: Dockerfile
      args: []
    expose:
      - "3000"
    environment:
      - NEXTAUTH_URL=${NEXTAUTH_URL}
    restart: unless-stopped